/* AUTH */
export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILUER";

export const SET_CURRENT_USER_START = "SET_CURRENT_USER_START";
export const SET_CURRENT_USER_SUCCESS = "SET_CURRENT_USER_SUCCESS";
export const SET_CURRENT_USER_FAILURE = "SET_CURRENT_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";

/* MODALs */
export const TOGGLE_DOCTOR_SEARCH_MODAL = "TOGGLE_DOCTOR_SEARCH_MODAL";
export const TOGGLE_VISIT_REQUEST_MODAL = "TOGGLE_VISIT_REQUEST_MODAL";
export const SET_VISIT_REQUEST_MODAL_DATA = "SET_VISIT_REQUEST_MODAL_DATA";
export const TOGGLE_DIAGNOSIS_CREATE_MODAL = "TOGGLE_DIAGNOSIS_CREATE_MODAL";
export const SET_DIAGNOSIS_CREATE_MODAL_PATIENT = "SET_DIAGNOSIS_CREATE_MODAL_PATIENT";

/* PROFILE */
export const GET_PROFILE_START = "GET_PROFILE_START";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
export const UNSET_PROFILE = "UNSET_PROFILE";

/* DOCTOR */
export const FETCH_DOCTORS_START = "FETCH_DOCTORS_START";
export const FETCH_DOCTORS_SUCCESS = "FETCH_DOCTORS_SUCCESS";
export const FETCH_DOCTORS_FAILURE = "FETCH_DOCTORS_FAILURE";

/* VISIT */
export const VISIT_REQUEST_START = "VISIT_REQUEST_START";
export const VISIT_REQUEST_SUCCESS = "VISIT_REQUEST_SUCCESS";
export const VISIT_REQUEST_FAILURE = "VISIT_REQUEST_FAILURE";

export const FETCH_VISIT_PENDING_REQUESTS_START = "FETCH_VISIT_PENDING_REQUESTS_START";
export const FETCH_VISIT_PENDING_REQUESTS_SUCCESS = "FETCH_VISIT_PENDING_REQUESTS_SUCCESS";
export const FETCH_VISIT_PENDING_REQUESTS_FAILURE = "FETCH_VISIT_PENDING_REQUESTS_FAILURE";

export const FETCH_VISIT_ACCEPTED_REQUESTS_START = "FETCH_VISIT_ACCEPTED_REQUESTS_START";
export const FETCH_VISIT_ACCEPTED_REQUESTS_SUCCESS = "FETCH_VISIT_ACCEPTED_REQUESTS_SUCCESS";
export const FETCH_VISIT_ACCEPTED_REQUESTS_FAILURE = "FETCH_VISIT_ACCEPTED_REQUESTS_FAILURE";

export const ACCEPT_VISIT_REQUEST_START = "ACCEPT_VISIT_REQUEST_START";
export const ACCEPT_VISIT_REQUEST_SUCCESS = "ACCEPT_VISIT_REQUEST_SUCCESS";
export const ACCEPT_VISIT_REQUEST_FAILURE = "ACCEPT_VISIT_REQUEST_FAILURE";

export const REJECT_VISIT_REQUEST_START = "REJECT_VISIT_REQUEST_START";
export const REJECT_VISIT_REQUEST_SUCCESS = "REJECT_VISIT_REQUEST_SUCCESS";
export const REJECT_VISIT_REQUEST_FAILURE = "REJECT_VISIT_REQUEST_FAILURE";

export const FETCH_VISIT_PARTIES_START = "FETCH_VISIT_PARTIES_START";
export const FETCH_VISIT_PARTIES_SUCCESS = "FETCH_VISIT_PARTIES_SUCCESS";
export const FETCH_VISIT_PARTIES_FAILURE = "FETCH_VISIT_PARTIES_FAILURE";

export * from "./auth/actions";
export * from "./modal/actions";
export * from "./profile/actions";
export * from "./doctor/actions";
export * from "./visit/actions";